version: '3.8'

services:
  code_processor:
    build: ./code_processor
    ports:
      - "8004:8004"
    networks:
      - plagiarism_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  embedding_api:
    build: ./embedding_api
    ports:
      - "8002:8002"
    networks:
      - plagiarism_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

#temporarily disabled, only needed for initial setup
  # indexer:
  #   build: ./indexer
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - shared:/app/shared
  #   networks:
  #     - plagiarism_network
  #   depends_on:
  #     - code_processor
  #     - embedding_api
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  search_api:
    build: ./search_api
    ports:
      - "8003:8003"
    volumes:
      - shared:/app/shared
    networks:
      - plagiarism_network
    depends_on:
      - code_processor
      - embedding_api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  llm_service:
    build: ./llm_service
    ports:
      - "8005:8005"
    volumes:
      - shared:/app/shared
    networks:
      - plagiarism_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  orchestrator:
    build: ./orchestrator
    ports:
      - "8000:8000"
    networks:
      - plagiarism_network
    depends_on:
      - search_api
      - llm_service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  evaluation:
    build: ./evaluation
    ports:
      - "8888:8888"
    volumes:
      - ./evaluation:/app/evaluation
    networks:
      - plagiarism_network
    depends_on:
      - orchestrator

volumes:
  shared:
    driver: local

networks:
  plagiarism_network:
    driver: bridge 